# Permalinks
permalink:        pretty

# Setup
title:            kamn.github.io
tagline:          Code and Stuff
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Samuel Miller
  url:            https://samuelamiller.com
  email:          kamn@users.noreply.github.com

# Custom vars
version:          0.0.1
github:
  repo:           https://github.com/kamn/kamn.github.io

markdown:         kramdown
highlighter:      rouge

theme: jekyll-theme-tactile